[tool.poetry]
name = "qbtapi"
version = "0.0.2"
description = "Pulls things from the QBittorrent API"
authors = [
    "James Hodgkinson <james@terminaloutcomes.com>",
]

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.27.1"

[tool.poetry.dependencies.splunk-hec]
url = "https://github.com/georgestarcher/Splunk-Class-httpevent/archive/refs/heads/master.tar.gz"

[tool.poetry.dev-dependencies]
pylint = "^2.14.0"
pytest = "^7.1.2"
black = "^22.3.0"
mypy = "^0.961"
types-requests = "^2.27.30"

[build-system]
requires = [
    "poetry-core>=1.0.0",
]
build-backend = "poetry.core.masonry.api"

[project]
name = "qbtapi"
description = "Pulls things from the QBittorrent API"
version = "0.0.2"
authors = [
    { name = "James Hodgkinson", email = "james@terminaloutcomes.com" },
]
