[tool.poetry]
name = "qbtapi"
version = "0.0.3"
description = "Pulls things from the QBittorrent API"
authors = [
    "James Hodgkinson <james@terminaloutcomes.com>",
]

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.28.1"

[tool.poetry.dependencies.pydantic]
extras = [
    "dotenv",
]
version = "^1.10.2"

[tool.poetry.dependencies.splunk-hec]
# temporary due to urllib3 dependency
url = "https://github.com/yaleman/Splunk-Class-httpevent/archive/refs/heads/yaleman/issue27.tar.gz"

[tool.poetry.dev-dependencies]
pylint = "^2.15.5"
pytest = "^7.2.0"
black = "^23.1.0"
mypy = "^1.0"
types-requests = "^2.28.11"
pylint-pydantic = "^0.1.4"
pylint-pytest = "^1.1.2"

[tool.pylint.MASTER]
max-line-length = 150
disable = "W0511,raise-missing-from"
extension-pkg-whitelist = "pydantic"
load-plugins = "pylint_pydantic,pylint_pytest"

[build-system]
requires = [
    "poetry-core>=1.0.0",
]
build-backend = "poetry.core.masonry.api"

[project]
name = "qbtapi"
description = "Pulls things from the QBittorrent API"
version = "0.0.3"
authors = [
    { name = "James Hodgkinson", email = "james@terminaloutcomes.com" },
]

[tool.mypy]
plugins = "pydantic.mypy"
