[tool.poetry]
name = "qbtapi"
version = "0.0.3"
description = "Pulls things from the QBittorrent API"
authors = [
    "James Hodgkinson <james@terminaloutcomes.com>",
]

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.28.1"
pydantic = {extras = ["dotenv"], version = "^1.9.2"}

[tool.poetry.dependencies.splunk-hec]
url = "https://github.com/georgestarcher/Splunk-Class-httpevent/archive/refs/heads/master.tar.gz"

[tool.poetry.dev-dependencies]
pylint = "^2.14.5"
pytest = "^7.1.2"
black = "^22.6.0"
mypy = "^0.971"
types-requests = "^2.28.9"
pylint-pydantic = "^0.1.4"
pylint-pytest = "^1.1.2"

[build-system]
requires = [
    "poetry-core>=1.0.0",
]
build-backend = "poetry.core.masonry.api"

[project]
name = "qbtapi"
description = "Pulls things from the QBittorrent API"
version = "0.0.2"
authors = [
    { name = "James Hodgkinson", email = "james@terminaloutcomes.com" },
]


[tool.pylint.MASTER]
max-line-length=150
disable="W0511,raise-missing-from"
extension-pkg-whitelist="pydantic"
# https://github.com/samuelcolvin/pydantic/issues/1961#issuecomment-759522422
load-plugins="pylint_pydantic,pylint_pytest"
